version: '3'
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3001:3001"
    networks:
      - mern-app
  web:
    image: "sqcc-backend"
    build: .
    command: "node app.js"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    links: [ mongo ]
    networks:
      - mern-app
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
